apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: epitechcontent/t-dop-600-worker:k8s
        resources:
            limits:
                memory: "256Mi"
        env:
            - name: REDIS_HOST
            - name: POSTGRES_HOST
            - name: POSTGRES_PORT
            - name: POSTGRES_DB
            - name: POSTGRES_USER
            - name: POSTGRES_PASSWORD